<?php

namespace App\Support;

/**
 * Why THIS course, specifically.
 *
 * A recommendation the student cannot compare is a recommendation they cannot act
 * on: "متاحة الآن ومناسبة لتقدمك" is true of every course on the list and
 * therefore tells them nothing. What they need is the one or two facts that make
 * each option different from the one next to it — what it opens, what it costs
 * them in effort, whether it is late, whether it protects their GPA.
 *
 * Everything here is computed from the student's own plan data. Nothing is
 * generated by the model, so nothing here can be invented.
 */
class CourseAdvantages
{
    /**
     * Order matters: the most decision-changing fact comes first.
     *
     * `balance` outranks `gpa_safe` because "متطلب جامعة أونلاين" tells the student
     * what the course IS — which already implies the lighter load — while "صعوبتها
     * منخفضة" on its own does not explain why it is in the list.
     */
    public const STRENGTH = ['unlocks', 'catch_up', 'balance', 'heavy', 'gpa_safe', 'light_load', 'core', 'elective'];

    /**
     * @param array{
     *     name?: string, type?: string, credit_hours?: int, difficulty_level?: int,
     *     unlocks?: int, unlocks_count?: int, path_unlocks?: int,
     *     unlocks_courses?: array<int, string>, course_semester?: ?int
     * } $course
     * @param array{student_semester?: int, is_probation?: bool} $context
     * @return list<array{key: string, icon: string, text: string}>
     */
    public static function for(array $course, array $context = []): array
    {
        $advantages = [];

        $direct = (int) ($course['unlocks'] ?? $course['unlocks_count'] ?? 0);
        $path = (int) ($course['path_unlocks'] ?? 0);
        $hours = (int) ($course['credit_hours'] ?? 0);
        $difficulty = max(1, min(5, (int) ($course['difficulty_level'] ?? 3)));
        $type = (string) ($course['type'] ?? '');
        $names = array_values(array_filter((array) ($course['unlocks_courses'] ?? [])));

        // 1. What it opens — the single most useful thing to know, because a
        //    postponed gateway course postpones everything behind it.
        if ($direct > 0) {
            $sample = $names === [] ? '' : ' (' . implode('، ', array_slice($names, 0, 2)) . ($direct > 2 ? '…' : '') . ')';
            $advantages[] = [
                'key' => 'unlocks',
                'icon' => '🔑',
                'text' => $direct === 1
                    ? "تفتح لك مادة لاحقة{$sample}"
                    : "تفتح لك {$direct} مواد لاحقة{$sample}",
            ];
        } elseif ($path > 0) {
            $advantages[] = [
                'key' => 'unlocks',
                'icon' => '🔗',
                'text' => "تؤثر في مسار يصل إلى {$path} مواد",
            ];
        }

        // 2. Late relative to the study plan: catching up now is what keeps the
        //    remaining terms from compounding.
        $planSemester = $course['course_semester'] ?? null;
        $studentSemester = (int) ($context['student_semester'] ?? 0);
        if ($planSemester !== null && $studentSemester > 0 && (int) $planSemester < $studentSemester) {
            $advantages[] = [
                'key' => 'catch_up',
                'icon' => '⏰',
                'text' => 'متأخرة عن فصلها في الخطة (الفصل ' . (int) $planSemester . ') — الأفضل تنجزها الآن',
            ];
        }

        $isUniversity = in_array($type, (array) config('academic_path_planner.balance.university_types', []), true);

        // 3. Effort, stated plainly in both directions. Skipped for university
        //    requirements: saying "online requirement" and "low difficulty" about
        //    the same course spends two of three lines on one fact.
        if ($difficulty <= 2 && !$isUniversity) {
            $advantages[] = [
                'key' => 'gpa_safe',
                'icon' => '📈',
                'text' => 'صعوبتها منخفضة — تساعد في حماية معدلك',
            ];
        } elseif ($difficulty >= 5) {
            $advantages[] = [
                'key' => 'heavy',
                'icon' => '⚠️',
                'text' => 'ثقيلة — خُذها مع مواد أخفّ ولا تجمعها مع مادة صعبة أخرى',
            ];
        }

        // 4. University requirements are delivered online here, which is exactly
        //    why they balance a term full of specialisation courses.
        if ($isUniversity) {
            $advantages[] = [
                'key' => 'balance',
                'icon' => '💻',
                'text' => 'متطلب جامعة (أونلاين) — أخفّ ويوازن حمل فصلك',
            ];
        }

        // 5. A one-hour course is cheap progress and worth naming as such.
        if ($hours === 1) {
            $advantages[] = [
                'key' => 'light_load',
                'icon' => '🪶',
                'text' => 'ساعة معتمدة واحدة — تضيف تقدّماً بأقل عبء',
            ];
        }

        if (in_array($type, ['compulsory', 'supporting'], true) && $direct === 0 && $path === 0) {
            $advantages[] = [
                'key' => 'core',
                'icon' => '📘',
                'text' => 'إجبارية في خطتك — لا بد منها للتخرج',
            ];
        }

        if ($type === 'elective' && $advantages === []) {
            $advantages[] = [
                'key' => 'elective',
                'icon' => '🎯',
                'text' => 'اختيارية — مرنة ويمكن تأجيلها إن ضاق جدولك',
            ];
        }

        if ($advantages === []) {
            $advantages[] = [
                'key' => 'core',
                'icon' => '✅',
                'text' => 'متاحة لك الآن ومتطلباتها مكتملة',
            ];
        }

        // Keep the strongest facts. Three lines is what a student reads; a longer
        // list is skimmed and stops informing the choice.
        usort($advantages, fn ($a, $b) => array_search($a['key'], self::STRENGTH, true) <=> array_search($b['key'], self::STRENGTH, true));

        return array_slice($advantages, 0, 3);
    }

    /**
     * The same advantages as one line, for the model prompt.
     *
     * The prompt has a fixed budget and every extra character competes with the
     * course catalogue, so this is deliberately compact.
     */
    public static function summary(array $course, array $context = []): string
    {
        return implode(' · ', array_map(
            fn (array $advantage) => $advantage['text'],
            self::for($course, $context)
        ));
    }
}
